### ISSUE TITLE
Starting minimal.launch fails by reading the description file

### ISSUE THREAD

**Issue by fuesschen** [turtlebot/turtlebot#125]
Everything is compiled successfully on ARM but try to start minimal.launch fails with the following output

```
odroid@odroid:~$ roslaunch turtlebot_bringup minimal.launch
WARNING: cannot create log directory [/home/odroid/.ros/log/246725f8-a828-11e3-abc3-2a1c760d4922]. Please set ROS_LOG_DIR to a writable location.
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/hydro/share/xacro/xacro.py", line 60, in <module>
    xacro.main()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/xacro/__init__.py", line 582, in main
    process_includes(doc, os.path.dirname(sys.argv[1]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/xacro/__init__.py", line 205, in process_includes
    filename = eval_text(elt.getAttribute('filename'), {})
  File "/opt/ros/hydro/lib/python2.7/dist-packages/xacro/__init__.py", line 430, in eval_text
    results.append(handle_extension(lex.next()[1][2:-1]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/xacro/__init__.py", line 418, in handle_extension
    return eval_extension("$(%s)" % s)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/xacro/__init__.py", line 58, in eval_extension
    return substitution_args.resolve_args(str, context=substitution_args_context, resolve_anon=False)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 299, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 312, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 145, in _find
    pkg_path = rp.get_path(args[0])
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 167, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: create_description
ROS path [0]=/opt/ros/hydro/share/ros
ROS path [1]=/home/odroid/catkin_ws/src
ROS path [2]=/opt/ros/hydro/share
ROS path [3]=/opt/ros/hydro/stacks
No handlers could be found for logger "roslaunch"
while processing /home/odroid/catkin_ws/src/turtlebot/turtlebot_bringup/launch/includes/robot.launch.xml:
while processing /home/odroid/catkin_ws/src/turtlebot/turtlebot_bringup/launch/includes/description.launch.xml:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/hydro/share/xacro/xacro.py '/home/odroid/catkin_ws/src/turtlebot/turtlebot_description/robots/kobuki_hexagons_kinect.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(arg urdf_file)" name="robot_description"/>
```

**Comment by bit-pirate** [comment]
From your error log:

```
File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 167, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: create_description
```

Looks like you are missing this package. Please make sure `create_description` is in ROS_PACKAGE_PATH / workspace.

**Comment by fuesschen** [comment]
thank you ros-hydro-create-description solves the problem
